spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: assignment_db
    password: 123456
    url: jdbc:oracle:thin:@192.168.0.100:1521:xe

logging:
  level:
    root: info
  file: ./log.txt
  pattern:
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'
    file: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'
